=== L2JPremium-stack/NEXORA_AION_FULL/game-server/data/static_data/spawns/spawns.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	<xs:element name="spawns" type="SpawnsData" />

	<xs:complexType name="SpawnsData">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="spawn_map" type="SpawnMap" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="unique-npc-id"><!-- a spawn entry must be unique per npc_id (see SpawnData#afterUnmarshal) -->
					<!-- entry with same npc_id may appear twice if one has custom="true" -->
					<xs:selector xpath="spawn" />
					<xs:field xpath="@npc_id" />
					<xs:field xpath="@custom" />
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SpawnMap">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="base_spawn" type="BaseSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="rift_spawn" type="RiftSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="siege_spawn" type="SiegeSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="vortex_spawn" type="VortexSpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="mercenary_spawn" type="MercenarySpawn" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ahserion_spawn" type="AhserionsFlightSpawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="map_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="BaseSpawn">
		<xs:sequence>
			<xs:element name="occupier_template" type="BaseOccupierTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="BaseOccupierTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="occupier" type="BaseOccupier" use="required" />
	</xs:complexType>
	<xs:complexType name="RiftSpawn">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="world" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexSpawn">
		<xs:sequence>
			<xs:element name="state_type" type="VortexStateTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="VortexStateTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="state" type="StateType"/>
	</xs:complexType>
	<xs:complexType name="AhserionsFlightSpawn">
		<xs:sequence>
			<xs:element name="ahserion_stage_spawn" type="AhserionStageSpawnTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="faction" type="PanesterraFaction"/>
	</xs:complexType>
	<xs:complexType name="AhserionStageSpawnTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="stage" type="xs:int"/>
	</xs:complexType>
	<xs:simpleType name="PanesterraFaction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BELUS"/>
			<xs:enumeration value="ASPIDA"/>
			<xs:enumeration value="ATANATOS"/>
			<xs:enumeration value="DISILLON"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="INVASION"/>
			<xs:enumeration value="PEACE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="SiegeSpawn">
		<xs:sequence>
			<xs:element name="siege_race" type="SiegeRaceTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="SiegeRaceTemplate">
		<xs:sequence>
			<xs:element name="siege_mod" type="SiegeModTemplate" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="SiegeRaceType" use="required"/>
	</xs:complexType>
	<xs:complexType name="SiegeModTemplate">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="mod" type="SiegeModType"/>
	</xs:complexType>
	<xs:complexType name="MercenarySpawn">
		<xs:sequence>
			<xs:element name="mercenary_race" type="MercenaryRace" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="siege_id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="MercenaryRace">
		<xs:sequence>
			<xs:element name="mercenary_zone" type="MercenaryZone" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>
	<xs:complexType name="MercenaryZone">
		<xs:sequence>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="zone" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Spawn">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
			<xs:element name="spot" type="SpawnSpotTemplate" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
		<xs:attribute name="pool" type="xs:int"/>
		<xs:attribute name="respawn_time" type="xs:int"/>
		<xs:attribute name="handler" type="SpawnHandlerType"/>
		<xs:attribute name="custom" type="xs:boolean" default="false"/>
		<xs:attribute name="difficult_id" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="SpawnSpotTemplate">
		<xs:sequence>
			<xs:element name="temporary_spawn" type="TemporarySpawn" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="h" type="HeadingType" default="0"/>
		<xs:attribute name="static_id" type="xs:int" default="0"/>
		<xs:attribute name="random_walk" type="xs:int" default="0"/>
		<xs:attribute name="walker_id" type="xs:string"/>
		<xs:attribute name="walker_index" type="xs:int" default="0"/>
		<xs:attribute name="fly" type="xs:int" default="0"/>
		<xs:attribute name="anchor" type="xs:string"/>
		<xs:attribute name="state" type="xs:int" default="0"/>
		<xs:attribute name="aerial_spawn" type="xs:boolean"/>
		<xs:attribute name="ai" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TemporarySpawn">
		<xs:attribute name="weekdays" type="WeekdayList"/>
		<xs:attribute name="spawn_time" type="xs:string"/>
		<xs:attribute name="despawn_time" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="WeekdayList">
		<xs:list itemType="Weekday" />
	</xs:simpleType>
	<xs:simpleType name="Weekday">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MONDAY"/>
			<xs:enumeration value="TUESDAY"/>
			<xs:enumeration value="WEDNESDAY"/>
			<xs:enumeration value="THURSDAY"/>
			<xs:enumeration value="FRIDAY"/>
			<xs:enumeration value="SATURDAY"/>
			<xs:enumeration value="SUNDAY"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeModType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PEACE"/>
			<xs:enumeration value="SIEGE"/>
			<xs:enumeration value="LANDING"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HeadingType">
		<xs:restriction base="xs:byte">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="120"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SiegeRaceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ELYOS"/>
			<xs:enumeration value="ASMODIANS"/>
			<xs:enumeration value="BALAUR"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SpawnHandlerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ATTACKER"/>
			<xs:enumeration value="BOSS"/>
			<xs:enumeration value="FLAG"/>
			<xs:enumeration value="GUARDIAN"/>
			<xs:enumeration value="MERCHANT"/>
			<xs:enumeration value="OUTRIDER"/>
			<xs:enumeration value="OUTRIDER_ENHANCED"/>
			<xs:enumeration value="RIFT"/>
			<xs:enumeration value="SENTINEL"/>
			<xs:enumeration value="STATIC"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== L2JPremium-stack/NEXORA_AION_FULL/game-server/data/static_data/spawns/Instances/310020000_Karamatis.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="310020000">
		<!-- Archon Legionary -->
		<spawn npc_id="205009">
			<spot x="127.0000" y="203.0000" z="225.0000" h="38" state="35" aerial_spawn="true"/>
			<spot x="164.0000" y="221.0000" z="220.0000" h="75" state="35" aerial_spawn="true"/>
			<spot x="164.0000" y="239.0000" z="220.0000" h="51" state="35" aerial_spawn="true"/>
			<spot x="165.8012" y="189.8012" z="203.0000" h="75" state="35" aerial_spawn="true"/>
			<spot x="175.0000" y="268.0000" z="212.0000" h="69" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205010">
			<spot x="109.0000" y="208.0000" z="213.0000" h="99" state="35" aerial_spawn="true"/>
			<spot x="143.0000" y="232.0000" z="199.0000" h="45" state="35" aerial_spawn="true"/>
			<spot x="151.8012" y="223.8012" z="213.0000" h="75" state="35" aerial_spawn="true"/>
			<spot x="185.0000" y="236.0000" z="223.0000" h="30" state="35" aerial_spawn="true"/>
			<spot x="188.0000" y="204.0000" z="219.0000" h="105" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Belpartan -->
		<spawn npc_id="205000">
			<spot x="85.0000" y="191.0000" z="231.6508" h="66"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205005">
			<spot x="27.0000" y="154.0000" z="228.0000" h="13" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205003">
			<spot x="40.0000" y="173.0000" z="228.0000" h="5" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205013">
			<spot x="122.0646" y="220.6141" z="220.3087" h="15" state="35" aerial_spawn="true"/>
			<spot x="127.8492" y="194.4565" z="225.7996" h="107" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205011">
			<spot x="140.3502" y="239.2481" z="217.5084" h="75" state="35" aerial_spawn="true"/>
			<spot x="146.7561" y="206.7927" z="217.5146" h="3" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Grunt -->
		<spawn npc_id="211044">
			<spot x="223.5400" y="283.9939" z="206.7366" h="41"/>
			<spot x="234.7777" y="285.2592" z="206.7123" h="42"/>
			<spot x="252.1250" y="214.8750" z="205.8205" h="109"/>
			<spot x="254.0000" y="300.0000" z="206.7753" h="30"/>
			<spot x="256.0000" y="303.0000" z="205.9827" h="60"/>
			<spot x="257.2039" y="241.8641" z="210.2859" h="49"/>
			<spot x="276.6125" y="295.5794" z="205.8498" h="98"/>
			<spot x="288.0000" y="229.0000" z="209.3701" h="38"/>
			<spot x="295.0000" y="248.0000" z="205.6915" h="72"/>
			<spot x="296.0000" y="276.0000" z="206.3569" h="21"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205018">
			<spot x="59.5000" y="181.7500" z="228.7547" h="80"/>
			<spot x="65.7500" y="179.3750" z="228.8462" h="56"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205019">
			<spot x="61.7500" y="176.3750" z="228.9820" h="58"/>
			<spot x="67.5000" y="185.7500" z="228.4363" h="81"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205001">
			<spot x="63.5000" y="183.7500" z="228.7197" h="86"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205002">
			<spot x="69.7500" y="181.3750" z="228.4128" h="70"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205014">
			<spot x="119.0540" y="218.6892" z="221.3638" h="16" state="35" aerial_spawn="true"/>
			<spot x="126.8243" y="199.8833" z="226.0447" h="86" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205007">
			<spot x="110.0000" y="206.0000" z="213.0000" h="38" state="35" aerial_spawn="true"/>
			<spot x="126.0000" y="205.0000" z="225.0000" h="99" state="35" aerial_spawn="true"/>
			<spot x="162.1988" y="219.1988" z="220.0000" h="15" state="35" aerial_spawn="true"/>
			<spot x="164.0000" y="188.0000" z="203.0000" h="15" state="35" aerial_spawn="true"/>
			<spot x="185.0000" y="238.0000" z="223.0000" h="90" state="35" aerial_spawn="true"/>
			<spot x="189.8012" y="202.1988" z="219.0000" h="45" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205012">
			<spot x="142.5667" y="239.7028" z="217.5245" h="76" state="35" aerial_spawn="true"/>
			<spot x="143.0366" y="206.9177" z="218.0496" h="2" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205008">
			<spot x="141.1988" y="233.8012" z="199.0000" h="105" state="35" aerial_spawn="true"/>
			<spot x="150.0000" y="222.0000" z="213.0000" h="15" state="35" aerial_spawn="true"/>
			<spot x="162.0000" y="240.0000" z="220.0000" h="111" state="35" aerial_spawn="true"/>
			<spot x="173.0000" y="267.0000" z="212.0000" h="8" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205015">
			<spot x="206.0000" y="211.6710" z="216.1000" h="30" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205016">
			<spot x="254.0000" y="303.0000" z="205.5542"/>
			<spot x="287.0000" y="231.0000" z="209.6033" h="99"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205017">
			<spot x="297.0000" y="278.0000" z="206.6896" h="81"/>
		</spawn>
	</spawn_map>
</spawns>

=== L2JPremium-stack/NEXORA_AION_FULL/game-server/data/static_data/spawns/Instances/300360000_Arena_of_Discipline.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="300360000">
		<!-- Blessed Relics -->
		<spawn npc_id="701216" respawn_time="105" difficult_id="1">
			<spot x="692.663" y="1770.740" z="219.014" aerial_spawn="true"/>
			<spot x="707.409" y="1779.437" z="165.419" aerial_spawn="true"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701221" respawn_time="105" difficult_id="2">
			<spot x="692.663" y="1770.740" z="219.014" aerial_spawn="true"/>
			<spot x="707.409" y="1779.437" z="165.419" aerial_spawn="true"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701226" respawn_time="105" difficult_id="3">
			<spot x="692.663" y="1770.740" z="219.014" aerial_spawn="true"/>
			<spot x="707.409" y="1779.437" z="165.419" aerial_spawn="true"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701215" respawn_time="105" difficult_id="1">
			<spot x="1848.173" y="1737.195" z="305.182"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701220" respawn_time="105" difficult_id="2">
			<spot x="1848.173" y="1737.195" z="305.182"/>
		</spawn>
		<!-- Blessed Relics -->
		<spawn npc_id="701225" respawn_time="105" difficult_id="3">
			<spot x="1848.173" y="1737.195" z="305.182"/>
		</spawn>
		<!-- Crater -->
		<spawn npc_id="701219" respawn_time="30" difficult_id="1">
			<spot x="676.005" y="1766.244" z="171.897" aerial_spawn="true"/>
			<spot x="680.167" y="1767.332" z="164.170" aerial_spawn="true"/>
			<spot x="682.348" y="1780.562" z="164.022" aerial_spawn="true"/>
			<spot x="682.538" y="1762.745" z="164.170" aerial_spawn="true"/>
			<spot x="691.514" y="1760.514" z="164.170" aerial_spawn="true"/>
			<spot x="693.787" y="1780.437" z="163.861" aerial_spawn="true"/>
			<spot x="695.261" y="1765.080" z="164.170" aerial_spawn="true"/>
			<spot x="697.315" y="1777.487" z="163.861" aerial_spawn="true"/>
			<spot x="700.407" y="1756.772" z="177.998" aerial_spawn="true"/>
			<spot x="701.967" y="1765.882" z="164.438" aerial_spawn="true"/>
			<spot x="703.459" y="1775.125" z="164.438" aerial_spawn="true"/>
			<spot x="706.059" y="1761.232" z="163.933" aerial_spawn="true"/>
			<spot x="707.120" y="1768.369" z="164.189" aerial_spawn="true"/>
			<spot x="711.216" y="1772.974" z="164.674" aerial_spawn="true"/>
		</spawn>
		<!-- Crater -->
		<spawn npc_id="701224" respawn_time="30" difficult_id="2">
			<spot x="676.005" y="1766.244" z="171.897" aerial_spawn="true"/>
			<spot x="680.167" y="1767.332" z="164.170" aerial_spawn="true"/>
			<spot x="682.348" y="1780.562" z="164.022" aerial_spawn="true"/>
			<spot x="682.538" y="1762.745" z="164.170" aerial_spawn="true"/>
			<spot x="691.514" y="1760.514" z="164.170" aerial_spawn="true"/>
			<spot x="693.787" y="1780.437" z="163.861" aerial_spawn="true"/>
			<spot x="695.261" y="1765.080" z="164.170" aerial_spawn="true"/>
			<spot x="697.315" y="1777.487" z="163.861" aerial_spawn="true"/>
			<spot x="700.407" y="1756.772" z="177.998" aerial_spawn="true"/>
			<spot x="701.967" y="1765.882" z="164.438" aerial_spawn="true"/>
			<spot x="703.459" y="1775.125" z="164.438" aerial_spawn="true"/>
			<spot x="706.059" y="1761.232" z="163.933" aerial_spawn="true"/>
			<spot x="707.120" y="1768.369" z="164.189" aerial_spawn="true"/>
			<spot x="711.216" y="1772.974" z="164.674" aerial_spawn="true"/>
		</spawn>
		<!-- Crater -->
		<spawn npc_id="701229" respawn_time="30" difficult_id="3">
			<spot x="676.005" y="1766.244" z="171.897" aerial_spawn="true"/>
			<spot x="680.167" y="1767.332" z="164.170" aerial_spawn="true"/>
			<spot x="682.348" y="1780.562" z="164.022" aerial_spawn="true"/>
			<spot x="682.538" y="1762.745" z="164.170" aerial_spawn="true"/>
			<spot x="691.514" y="1760.514" z="164.170" aerial_spawn="true"/>
			<spot x="693.787" y="1780.437" z="163.861" aerial_spawn="true"/>
			<spot x="695.261" y="1765.080" z="164.170" aerial_spawn="true"/>
			<spot x="697.315" y="1777.487" z="163.861" aerial_spawn="true"/>
			<spot x="700.407" y="1756.772" z="177.998" aerial_spawn="true"/>
			<spot x="701.967" y="1765.882" z="164.438" aerial_spawn="true"/>
			<spot x="703.459" y="1775.125" z="164.438" aerial_spawn="true"/>
			<spot x="706.059" y="1761.232" z="163.933" aerial_spawn="true"/>
			<spot x="707.120" y="1768.369" z="164.189" aerial_spawn="true"/>
			<spot x="711.216" y="1772.974" z="164.674" aerial_spawn="true"/>
		</spawn>
		<!-- Lava Floor -->
		<spawn npc_id="701218" respawn_time="30" difficult_id="1">
			<spot x="687.888" y="1766.859" z="163.000"/>
			<spot x="688.366" y="1777.590" z="163.000"/>
			<spot x="699.176" y="1772.244" z="163.000"/>
			<spot x="707.605" y="1779.565" z="163.673"/>
		</spawn>
		<!-- Lava Floor -->
		<spawn npc_id="701223" respawn_time="30" difficult_id="2">
			<spot x="687.888" y="1766.859" z="163.000"/>
			<spot x="688.366" y="1777.590" z="163.000"/>
			<spot x="699.176" y="1772.244" z="163.000"/>
			<spot x="707.605" y="1779.565" z="163.673"/>
		</spawn>
		<!-- Lava Floor -->
		<spawn npc_id="701228" respawn_time="30" difficult_id="3">
			<spot x="687.888" y="1766.859" z="163.000"/>
			<spot x="688.366" y="1777.590" z="163.000"/>
			<spot x="699.176" y="1772.244" z="163.000"/>
			<spot x="707.605" y="1779.565" z="163.673"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="218693" respawn_time="105" difficult_id="1">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="218706" respawn_time="105" difficult_id="2">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="218719" respawn_time="105" difficult_id="3">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Red Sand Tog -->
		<spawn npc_id="233058" respawn_time="105" difficult_id="4">
			<spot x="1856.197" y="1071.305" z="337.287" h="90"/>
		</spawn>
		<!-- Tog Manger -->
		<spawn npc_id="218757" respawn_time="105">
			<spot x="1853.310" y="1072.531" z="337.734"/>
		</spawn>
		<!-- Treasure Box -->
		<spawn npc_id="218802" respawn_time="105">
			<spot x="297.641" y="1239.489" z="267.572"/>
		</spawn>
	</spawn_map>
</spawns>

=== L2JPremium-stack/NEXORA_AION_FULL/game-server/data/static_data/spawns/Instances/320010000_Ataxiar.xml
<?xml version="1.0" encoding="utf-8"?>
<spawns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../spawns.xsd">
	<spawn_map map_id="320010000">
		<!-- Archon Legionary -->
		<spawn npc_id="205036">
			<spot x="447" y="412" z="229" h="45" state="1"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205035">
			<spot x="442" y="413" z="230" state="1"/>
			<spot x="451" y="415" z="229" h="45" state="1"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205024">
			<spot x="444" y="409" z="230" h="45" state="1"/>
			<spot x="448" y="420" z="230" state="1"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205021">
			<spot x="341" y="289" z="243" h="90" state="35" aerial_spawn="true"/>
			<spot x="347" y="246" z="238" h="90" state="35" aerial_spawn="true"/>
			<spot x="365" y="299" z="215" h="90" state="35" aerial_spawn="true"/>
			<spot x="368" y="380" z="246" h="90" state="35" aerial_spawn="true"/>
			<spot x="389" y="258" z="234" h="90" state="35" aerial_spawn="true"/>
			<spot x="400" y="359" z="213" h="90" state="35" aerial_spawn="true"/>
			<spot x="400" y="394" z="227" h="90" state="35" aerial_spawn="true"/>
			<spot x="405" y="381" z="246" h="90" state="35" aerial_spawn="true"/>
			<spot x="410" y="355" z="264" h="90" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205023">
			<spot x="444" y="416" z="229" state="1"/>
		</spawn>
		<!-- Archon Legionary -->
		<spawn npc_id="205022">
			<spot x="324" y="342" z="212" h="90" state="35" aerial_spawn="true"/>
			<spot x="338" y="379" z="233" h="90" state="35" aerial_spawn="true"/>
			<spot x="339" y="335" z="244" h="90" state="35" aerial_spawn="true"/>
			<spot x="346" y="288" z="214" h="90" state="35" aerial_spawn="true"/>
			<spot x="358" y="242" z="210" h="90" state="35" aerial_spawn="true"/>
			<spot x="362" y="344" z="219" h="90" state="35" aerial_spawn="true"/>
			<spot x="368" y="290" z="216" h="90" state="35" aerial_spawn="true"/>
			<spot x="378" y="324" z="249" h="90" state="35" aerial_spawn="true"/>
			<spot x="405" y="345" z="229" h="90" state="35" aerial_spawn="true"/>
			<spot x="409" y="293" z="253" h="90" state="35" aerial_spawn="true"/>
			<spot x="439" y="374" z="239" h="90" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205005">
			<spot x="339" y="298" z="243" h="90" state="35" aerial_spawn="true"/>
			<spot x="346" y="255" z="238" h="90" state="35" aerial_spawn="true"/>
			<spot x="380" y="255" z="234" h="90" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Centurion -->
		<spawn npc_id="205003">
			<spot x="364" y="294" z="215" h="90" state="35" aerial_spawn="true"/>
			<spot x="375" y="383" z="246" h="90" state="35" aerial_spawn="true"/>
			<spot x="397" y="352" z="213" h="90" state="35" aerial_spawn="true"/>
			<spot x="398" y="380" z="246" h="90" state="35" aerial_spawn="true"/>
			<spot x="406" y="395" z="227" h="90" state="35" aerial_spawn="true"/>
			<spot x="409" y="362" z="264" h="90" state="35" aerial_spawn="true"/>
		</spawn>
		<!-- Hagen -->
		<spawn npc_id="205020">
			<spot x="434.75" y="399.5" z="235" h="25"/>
		</spawn>
		<!-- Legionary -->
		<spawn npc_id="205004">
			<spot x="332" y="343" z="212" h="90" state="35" aerial_spawn="true"/>
			<spot x="332" y="373" z="233" h="90" state="35" aerial_spawn="true"/>
			<spot x="340" y="345" z="244" h="90" state="35" aerial_spawn="true"/>
			<spot x="350" y="295" z="214" h="90" state="35" aerial_spawn="true"/>
			<spot x="362" y="247" z="210" h="90" state="35" aerial_spawn="true"/>
			<spot x="369" y="344" z="219" h="90" state="35" aerial_spawn="true"/>
			<spot x="372" y="294" z="216" h="90" state="35" aerial_spawn="true"/>
			<spot x="382" y="324" z="249" h="90" state="35" aerial_spawn="true"/>
			<spot x="406" y="285" z="253" h="90" state="35" aerial_spawn="true"/>
			<spot x="413" y="351" z="229" h="90" state="35" aerial_spawn="true"/>
			<spot x="432" y="376" z="239" h="90" state="35" aerial_spawn="true"/>
		</spawn>
	</spawn_map>
</spawns>
